<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Inflector;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $name
 * @property string $article
 * @property string|null $decsription
 * @property string $slug
 * @property int $price
 * @property string $meta_title
 * @property string $meta_desc
 * @property string $meta_keywords
 * @property int $created_at
 * @property int $updated_at
 * @property int|null $group_id
 *
 * @property CategoryProduct[] $categoryProducts
 * @property Group $group
 * @property PropertyValue[] $propertyValues
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class
            ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'article',  'price', ], 'required'],
            [['decsription'], 'string'],
            [['price',  'group_id'], 'integer'],
            [['name', 'article', 'slug', 'meta_title', 'meta_desc', 'meta_keywords'], 'string', 'max' => 255],
            [['article', 'slug'], 'unique'],
            [['group_id'], 'exist', 'skipOnError' => true, 'targetClass' => Group::className(), 'targetAttribute' => ['group_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'article' => 'Article',
            'decsription' => 'Decsription',
            'slug' => 'Slug',
            'price' => 'Price',
            'meta_title' => 'Meta Title',
            'meta_desc' => 'Meta Desc',
            'meta_keywords' => 'Meta Keywords',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'group_id' => 'Group ID',
        ];
    }

    /**
     * Gets query for [[CategoryProducts]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryProducts()
    {
        return $this->hasMany(CategoryProduct::className(), ['id_product' => 'id']);
    }

    /**
     * Gets query for [[Group]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(Group::className(), ['id' => 'group_id']);
    }

    /**
     * Gets query for [[PropertyValues]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPropertyValues()
    {
        return $this->hasMany(PropertyValue::className(), ['id_product' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->slug = $this->slug ? $this->slug : Inflector::slug($this->name);
        $this->decsription = $this->decsription ? $this->decsription : $this->name;
        $this->meta_title = $this->meta_title ? $this->meta_title : $this->name;
        $this->meta_keywords = $this->meta_keywords ? $this->meta_keywords : $this->name;
        $this->meta_desc = $this->meta_desc ? $this->meta_desc : $this->name;



        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
